/**
 * Scalar value types supported in filter expressions.
 *
 * `Date` is included for direct code usage (e.g. `{ createdAt: { $gt: new Date() } }`).
 * The URL parser produces ISO strings, not `Date` instances.
 * Adapters are responsible for handling both: convert `Date` to their native format
 * (e.g. `.toISOString()` for SQL params, native `Date` for MongoDB).
 */
export type Primitive = string | number | boolean | null | RegExp | Date

/** All comparison operators supported by the filter format. */
export type ComparisonOp =
  | '$eq'
  | '$ne'
  | '$gt'
  | '$gte'
  | '$lt'
  | '$lte'
  | '$in'
  | '$nin'
  | '$regex'
  | '$exists'

/**
 * Per-field typed operator map. When `V` is the field's value type, operators
 * are constrained accordingly:
 * - `$regex` is only available when `V` extends `string`
 * - `$gt/$gte/$lt/$lte` are only available when `V` extends `number | string | Date`
 */
export type FieldOpsFor<V> = {
  $eq?: V
  $ne?: V
  $in?: V[]
  $nin?: V[]
  $exists?: boolean
} & (V extends string ? { $regex?: RegExp | string } : {}) &
  (V extends number | string | Date
    ? { $gt?: V; $gte?: V; $lt?: V; $lte?: V }
    : {})

/** Untyped operator map. */
export type FieldOps = FieldOpsFor<Primitive>

/** A field can hold a bare primitive (implicit $eq) or an explicit operator map. */
export type FieldValue = Primitive | FieldOps

/**
 * A filter expression is either a comparison leaf or a logical branch.
 * `T` is the entity shape — provides type-safe field names and value types.
 * Defaults to `Record<string, unknown>` (untyped).
 */
export type FilterExpr<T = Record<string, unknown>> =
  | ComparisonNode<T>
  | LogicalNode<T>

/**
 * Leaf node: one or more field comparisons.
 * When `T` is typed, only known keys are allowed.
 * When untyped (default), any string key is accepted.
 */
export type ComparisonNode<T = Record<string, unknown>> = {
  [K in keyof T & string]?: T[K] | FieldOpsFor<T[K]>
}

/**
 * Branch node: logical combination of child expressions.
 * Each variant forbids the other logical keys via `never` to prevent
 * mixing comparison fields with logical operators at the type level.
 */
export type LogicalNode<T = Record<string, unknown>> =
  | { $and: FilterExpr<T>[]; $or?: never; $not?: never }
  | { $or: FilterExpr<T>[]; $and?: never; $not?: never }
  | { $not: FilterExpr<T>; $and?: never; $or?: never }

/** Known aggregate function names. Consumers may support additional functions via the (string & {}) escape hatch. */
export type AggregateFn = 'sum' | 'count' | 'avg' | 'min' | 'max'

/** A single aggregate function call within $select. */
export interface AggregateExpr {
  /** Function name (sum, count, avg, min, max, or custom). */
  $fn: AggregateFn | (string & {})
  /** Field to aggregate. '*' for count(*). */
  $field: string
  /** Alias for the result. Auto-generated by URL parser if omitted. */
  $as?: string
}

/**
 * Projection definition.
 * - Array form: inclusion list with optional aggregates.
 *   Plain strings select fields; AggregateExpr objects define computed columns.
 * - Object form: inclusion/exclusion map (0 or 1 per field). No aggregates in this form.
 */
export type SelectExpr<T = Record<string, unknown>> =
  | ((keyof T & string) | AggregateExpr)[]
  | Partial<Record<keyof T & string, 0 | 1>>

/** Query controls (pagination, projection, sorting, grouping). Generic `T` constrains field names. */
export interface UniqueryControls<
  T = Record<string, unknown>,
  Nav extends Record<string, unknown> = Record<string, unknown>,
> {
  $sort?: Partial<Record<keyof T & string, 1 | -1>>
  $skip?: number
  $limit?: number
  $count?: boolean
  $select?: SelectExpr<T>
  /** Fields to group by for aggregate queries. */
  $groupBy?: (keyof T & string)[]
  /** Relations to populate alongside the query. */
  $with?: TypedWithRelation<Nav>[]
  /** Pass-through for unknown $-prefixed keywords. */
  [key: `$${string}`]: unknown
}

/**
 * Canonical query representation.
 * When `name` is present this is a nested relation (sub-query inside `$with`).
 * When absent it is the root query.
 */
export interface Uniquery<
  T = Record<string, unknown>,
  Nav extends Record<string, unknown> = Record<string, unknown>,
> {
  /** Relation name. Present only for nested `$with` sub-queries. */
  name?: string
  filter?: FilterExpr<T>
  controls?: UniqueryControls<T, Nav>
  /** Pre-computed insights. */
  insights?: UniqueryInsights
}

/** Unwrap array types to get the element type for nav props. */
export type NavTarget<T> = T extends Array<infer U> ? U : T

/**
 * A typed $with relation entry.
 * When Nav is typed (from __navProps), name is constrained to known nav prop keys.
 * Each entry gets its own filter/controls typed to the target entity.
 * Falls back to untyped WithRelation when Nav has no known keys.
 */
export type TypedWithRelation<Nav extends Record<string, unknown>> =
  [keyof Nav & string] extends [never]
    ? WithRelation | string
    : {
        [K in keyof Nav & string]: {
          name: K
          filter?: FilterExpr<NavTarget<Nav[K]> extends { __ownProps: infer F } ? F : Record<string, unknown>>
          controls?: UniqueryControls<
            NavTarget<Nav[K]> extends { __ownProps: infer F } ? F : Record<string, unknown>,
            NavTarget<Nav[K]> extends { __navProps: infer N extends Record<string, unknown> } ? N : Record<string, unknown>
          >
          insights?: UniqueryInsights
        }
      }[keyof Nav & string] | (keyof Nav & string)

/** Untyped $with relation — used when Nav generic is not provided. */
export type WithRelation = {
  name: string
  filter?: FilterExpr
  controls?: UniqueryControls
  insights?: UniqueryInsights
}

/**
 * Insight operator includes comparison ops, control ops ($-prefixed),
 * and aggregate function names (bare, e.g. 'sum', 'avg').
 */
export type InsightOp = ComparisonOp | '$select' | '$order' | '$with' | '$groupBy' | AggregateFn | (string & {})

/** Map of field names to the set of operators used on that field. */
export type UniqueryInsights = Map<string, Set<InsightOp>>
