/**
 * Scalar value types supported in filter expressions.
 *
 * `Date` is included for direct code usage (e.g. `{ createdAt: { $gt: new Date() } }`).
 * The URL parser produces ISO strings, not `Date` instances.
 * Adapters are responsible for handling both: convert `Date` to their native format
 * (e.g. `.toISOString()` for SQL params, native `Date` for MongoDB).
 */
export type Primitive = string | number | boolean | null | RegExp | Date

/** All comparison operators supported by the filter format. */
export type ComparisonOp =
  | '$eq'
  | '$ne'
  | '$gt'
  | '$gte'
  | '$lt'
  | '$lte'
  | '$in'
  | '$nin'
  | '$regex'
  | '$exists'

/**
 * Per-field typed operator map. When `V` is the field's value type, operators
 * are constrained accordingly:
 * - `$regex` is only available when `V` extends `string`
 * - `$gt/$gte/$lt/$lte` are only available when `V` extends `number | string | Date`
 */
export type FieldOpsFor<V> = {
  $eq?: V
  $ne?: V
  $in?: V[]
  $nin?: V[]
  $exists?: boolean
} & (V extends string ? { $regex?: RegExp | string } : {}) &
  (V extends number | string | Date
    ? { $gt?: V; $gte?: V; $lt?: V; $lte?: V }
    : {})

/** Untyped operator map. */
export type FieldOps = FieldOpsFor<Primitive>

/** A field can hold a bare primitive (implicit $eq) or an explicit operator map. */
export type FieldValue = Primitive | FieldOps

/**
 * A filter expression is either a comparison leaf or a logical branch.
 * `T` is the entity shape — provides type-safe field names and value types.
 * Defaults to `Record<string, unknown>` (untyped).
 */
export type FilterExpr<T = Record<string, unknown>> =
  | ComparisonNode<T>
  | LogicalNode<T>

/**
 * Leaf node: one or more field comparisons.
 * When `T` is typed, only known keys are allowed.
 * When untyped (default), any string key is accepted.
 */
export type ComparisonNode<T = Record<string, unknown>> = {
  [K in keyof T & string]?: T[K] | FieldOpsFor<T[K]>
}

/**
 * Branch node: logical combination of child expressions.
 * The `never` members allow at most one logical key per object at the type
 * level (`{ $and, $or }` is rejected); comparison fields may still sit
 * alongside it (`{ id: 1, $or: [...] }`). At runtime every member of a node
 * is ANDed, so several logical keys in one object are accepted and combined.
 */
export type LogicalNode<T = Record<string, unknown>> =
  | { $and: FilterExpr<T>[]; $or?: never; $not?: never }
  | { $or: FilterExpr<T>[]; $and?: never; $not?: never }
  | { $not: FilterExpr<T>; $and?: never; $or?: never }

/** Known aggregate function names. Consumers may support additional functions via the (string & {}) escape hatch. */
export type AggregateFn = 'sum' | 'count' | 'avg' | 'min' | 'max'

/** A single aggregate function call within $select. Generic params preserve literal types for result inference. */
export interface AggregateExpr<
  Fn extends string = AggregateFn | (string & {}),
  Field extends string = string,
  Alias extends string = string,
> {
  /** Function name (sum, count, avg, min, max, or custom). */
  $fn: Fn
  /** Field to aggregate. '*' for count(*). */
  $field: Field
  /** Alias for the result. Auto-generated by URL parser if omitted. */
  $as?: Alias
}

/** Calendar units a bucket truncates to. */
export type BucketUnit = 'day' | 'week' | 'month' | 'quarter' | 'year'

/** First day of a `week` bucket (ISO 8601 default: 'mon'). */
export type WeekStart = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'

/**
 * `YYYY-MM-DD`: the local calendar date of the bucket's first day, the same
 * format for every unit. Zero-padded, so a plain string sort is chronological.
 */
export type CalendarBucketLabel = string

/**
 * A calendar bucket over an epoch-ms timestamp field: a derived grouping
 * dimension. Lives in an aggregate query's `$select` and is grouped by its
 * alias in `$groupBy`. Its value is a {@link CalendarBucketLabel}, or `null`
 * when the source is null/missing or outside the supported instant range.
 */
export interface BucketExpr<Field extends string = string, Alias extends string = string> {
  /** Calendar unit to truncate to. */
  $bucket: BucketUnit
  /** Source timestamp field (epoch milliseconds). */
  $field: Field
  /** IANA time zone name; default 'UTC'. */
  $tz?: string
  /** First day of the week. Only with `$bucket: 'week'`; default 'mon'. */
  $weekStart?: WeekStart
  /** Output alias; default `${unit}_${field}` (required when `$field` contains '.'). */
  $as?: Alias
}

/** A computed `$select` entry: a row-reducing aggregate or a per-row calendar bucket. */
export type ComputedExpr = AggregateExpr | BucketExpr

/**
 * Projection definition.
 * - Array form: inclusion list with optional computed columns.
 *   Plain strings select fields; AggregateExpr / BucketExpr objects define computed columns
 *   (buckets are valid only in aggregate queries).
 * - Object form: inclusion/exclusion map (0 or 1 per field). No computed columns in this form.
 */
export type SelectExpr<T = Record<string, unknown>> =
  | ((keyof T & string) | AggregateExpr | BucketExpr<keyof T & string>)[]
  | Partial<Record<keyof T & string, 0 | 1>>

/** Query controls (pagination, projection, sorting, grouping). Generic `T` constrains field names. */
export interface UniqueryControls<
  T = Record<string, unknown>,
  Nav extends Record<string, unknown> = Record<string, unknown>,
> {
  $sort?: Partial<Record<keyof T & string, 1 | -1>>
  $skip?: number
  $limit?: number
  $count?: boolean
  $select?: SelectExpr<T>
  /** Fields (or calendar-bucket aliases from `$select`) to group by for aggregate queries. */
  $groupBy?: ((keyof T & string) | (string & {}))[]
  /** Post-aggregation filter. Operates on aggregate aliases and dimension fields. */
  $having?: FilterExpr
  /** Relations to populate alongside the query. */
  $with?: TypedWithRelation<Nav>[]
  /** Pass-through for unknown $-prefixed keywords. */
  [key: `$${string}`]: unknown
}

/**
 * Canonical query representation.
 * When `name` is present this is a nested relation (sub-query inside `$with`).
 * When absent it is the root query.
 */
export interface Uniquery<
  T = Record<string, unknown>,
  Nav extends Record<string, unknown> = Record<string, unknown>,
> {
  /** Relation name. Present only for nested `$with` sub-queries. */
  name?: string
  filter?: FilterExpr<T>
  controls?: UniqueryControls<T, Nav>
  /** Pre-computed insights. */
  insights?: UniqueryInsights
}

/** Unwrap array types to get the element type for nav props. */
export type NavTarget<T> = T extends Array<infer U> ? U : T

/**
 * A typed $with relation entry.
 * When Nav is typed (from __navProps), name is constrained to known nav prop keys.
 * Each entry gets its own filter/controls typed to the target entity.
 * Falls back to untyped WithRelation when Nav has no known keys.
 */
export type TypedWithRelation<Nav extends Record<string, unknown>> =
  [keyof Nav & string] extends [never]
    ? WithRelation | string
    : {
        [K in keyof Nav & string]: {
          name: K
          filter?: FilterExpr<NavTarget<Nav[K]> extends { __ownProps: infer F } ? F : Record<string, unknown>>
          controls?: UniqueryControls<
            NavTarget<Nav[K]> extends { __ownProps: infer F } ? F : Record<string, unknown>,
            NavTarget<Nav[K]> extends { __navProps: infer N extends Record<string, unknown> } ? N : Record<string, unknown>
          >
          insights?: UniqueryInsights
        }
      }[keyof Nav & string] | (keyof Nav & string)

/** Untyped $with relation — used when Nav generic is not provided. */
export type WithRelation = {
  name: string
  filter?: FilterExpr
  controls?: UniqueryControls
  insights?: UniqueryInsights
}

/**
 * Insight operator includes comparison ops, control ops ($-prefixed),
 * and aggregate function names (bare, e.g. 'sum', 'avg').
 */
export type InsightOp = ComparisonOp | '$select' | '$order' | '$with' | '$groupBy' | '$having' | '$bucket' | AggregateFn | (string & {})

/** Map of field names to the set of operators used on that field. */
export type UniqueryInsights = Map<string, Set<InsightOp>>

/**
 * Aggregate query controls. Separate from UniqueryControls: $groupBy is required, $with is forbidden.
 *
 * `$groupBy` entries are dimension fields or calendar-bucket aliases declared in `$select`.
 * The constraint admits any string because TypeScript cannot relate a sibling `$as`
 * literal; use {@link ValidGroupBy} in a signature to restore the narrowing.
 */
export interface AggregateControls<
  T = Record<string, unknown>,
  D extends keyof T & string = keyof T & string,
  M extends keyof T & string = keyof T & string,
> {
  $groupBy: (D | (string & {}))[]
  $select?: (D | AggregateExpr<AggregateFn, M | '*'> | BucketExpr<D>)[]
  $having?: FilterExpr
  $sort?: Record<string, 1 | -1>
  $skip?: number
  $limit?: number
  $count?: boolean
  [key: `$${string}`]: unknown
}

/** Aggregate query — no name (can't nest), no Nav (no $with). */
export interface AggregateQuery<
  T = Record<string, unknown>,
  D extends keyof T & string = keyof T & string,
  M extends keyof T & string = keyof T & string,
> {
  filter?: FilterExpr<T>
  controls: AggregateControls<T, D, M>
  insights?: UniqueryInsights
}

/**
 * Resolve the output alias of a computed `$select` entry (type-level twin of `resolveAlias`).
 * Uses `$as` if provided, otherwise `{fn}_{field}` for aggregates and `{unit}_{field}` for
 * buckets, with `'*'` spelled `star` (`count(*)` → `count_star`).
 */
export type ResolveAlias<A> =
  A extends { $as: infer Alias extends string } ? Alias
  : A extends { $fn: infer Fn extends string; $field: infer F extends string } ? `${Fn}_${F extends '*' ? 'star' : F}`
  : A extends { $bucket: infer U extends string; $field: infer F extends string } ? `${U}_${F extends '*' ? 'star' : F}`
  : string

/** Aliases of the calendar buckets in a `$select` array type. */
type BucketAliasesOf<Select> = Select extends readonly unknown[]
  ? ResolveAlias<Extract<Select[number], BucketExpr>>
  : never

/**
 * Validation type for aggregate signatures: maps each `$groupBy` entry of `Q` that is
 * neither a dimension (`D`) nor the alias of a calendar bucket in `Q['controls']['$select']`
 * to `never`. Intersect it with the inferred query so a typo fails to compile:
 *
 * ```ts
 * aggregate<const Q extends AggregateQuery<T>>(q: Q & ValidGroupBy<T, Q>): ...
 * ```
 */
export type ValidGroupBy<T, Q, D extends string = keyof T & string> =
  Q extends { controls: { $groupBy: infer G extends readonly unknown[]; $select?: infer S } }
    ? {
        controls: {
          $groupBy: { [K in keyof G]: G[K] extends D | BucketAliasesOf<S> ? G[K] : never }
        }
      }
    : unknown

/**
 * Infer the result row type from an aggregate query's $select.
 * Dimension fields preserve their original type from T.
 * Aggregate expressions: min/max preserve original type, others → number.
 * Calendar buckets: {@link CalendarBucketLabel}, `| null` when the source is optional or nullable.
 */
export type AggregateResult<
  T,
  Select extends readonly (string | AggregateExpr | BucketExpr)[],
> =
  { [K in Extract<Select[number], string> & keyof T]: T[K] }
  & { [A in Extract<Select[number], AggregateExpr> as ResolveAlias<A>]:
      A extends { $fn: 'min' | 'max'; $field: infer F extends keyof T & string } ? T[F] : number
    }
  & { [B in Extract<Select[number], BucketExpr> as ResolveAlias<B>]:
      B extends { $field: infer F extends keyof T & string }
        ? null extends T[F] ? CalendarBucketLabel | null
          : undefined extends T[F] ? CalendarBucketLabel | null
          : CalendarBucketLabel
        : CalendarBucketLabel | null
    }
